name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        architecture: 'x64' # optional, x64 or x86. If not specified, x64 will be used by default
        
    - run: npm install
    
    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.3.9
      with:
        source: Tailspin.SpaceGame.Web/wwwroot/css/site.scss
        destination: Tailspin.SpaceGame.Web/wwwroot/css/site.css
    
    - name: Run gulp tasks
      uses: elstudio/actions-js-build/build@v4
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration release 
    
    - name: Publish
      run: dotnet publish --no-build --configuration release 
      
    - uses: papeloto/action-zip@v1
      with:
        files: Tailspin.SpaceGame.Web/bin/Release/netcoreapp3.1/publish/
        recursive: true
        dest: result.zip
        
    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApp1
        path: ${{ github.workspace }}/result.zip
        
    - name: Test
      run: dotnet test --no-build --verbosity normal
